$id: http://realestate.yodata.me/schema/ApplicationProfile.yaml
title: Thing
summary: The root type of all Things.
description: a solid profile document
type: object
required:
  - id
  - type
  - inbox
  - outbox
properties:
  '#me':
    type: object
    required:
      - type
    properties:
      type:
        type: string
        example: SoftwareApplication
        x-parser-schema-id: <anonymous-schema-482>
      inbox:
        description: URI to your Linked-Data-Notifications Inbox
        type: string
        example: /inbox/
        default: /inbox/
        x-parser-schema-id: <anonymous-schema-483>
      outbox:
        description: URI to your Linked-Data-Notifications Outbox
        type: string
        example: /outbox/
        default: /outbox/
        x-parser-schema-id: <anonymous-schema-484>
      storage:
        description: URI to your storage root.
        type: string
        example: /
        default: /
        x-parser-schema-id: <anonymous-schema-485>
      preferencesFile:
        description: URI to shared application prefs.
        type: string
        example: /settings/prefs
        x-parser-schema-id: <anonymous-schema-486>
      account:
        description: discoverable solid:account root
        type: string
        example: /
        x-parser-schema-id: <anonymous-schema-487>
      privateTypeIndex:
        description: type index for your private use
        type: string
        example: /settings/privateTypeIndex
        x-parser-schema-id: <anonymous-schema-488>
      publicTypeIndex:
        description: shared, discoverable type index
        type: string
        example: /settings/publicTypeIndex
        x-parser-schema-id: <anonymous-schema-489>
      permissions:
        description: Permissions required by an linked-data application or service.
        x-enumeration:
          - name: profile:read
            description: grantee can read the owner's profile data.
          - name: profile:write
            description: grantee can modify the owner's profile data.
          - name: lead
            description: grantee can read, write and modify leads.
          - name: contact
            description: grantee can read, write and modify contacts.
          - name: website:events
            description: grantee can read, write and modify website events.
        type: array
        items:
          type: object
          enum:
            - profile:read
            - profile:write
            - lead
            - contact
            - website:events
          x-parser-schema-id: <anonymous-schema-491>
        x-parser-schema-id: <anonymous-schema-490>
    x-parser-schema-id: <anonymous-schema-481>
  '@id':
    type: string
    format: uri
    description: the liked data uri for the Thing
    x-parser-schema-id: <anonymous-schema-160>
  account:
    description: discoverable solid:account root
    type: string
    example: /
    x-parser-schema-id: <anonymous-schema-499>
  id:
    type: string
    format: uri
    example: https://user.example.com/profile/card#me
    x-parser-schema-id: <anonymous-schema-493>
  inbox:
    description: discoverable uri to your LDN inbox
    type: string
    example: /inbox/
    x-parser-schema-id: <anonymous-schema-495>
  outbox:
    description: discoverable uri to your LDN outbox
    type: string
    example: /outbox/
    x-parser-schema-id: <anonymous-schema-496>
  permissions:
    description: the subscription types required by your service.
    type: array
    items:
      type: string
      enum:
        - profile:read
        - contact
        - lead
        - listing
      x-parser-schema-id: <anonymous-schema-503>
    x-parser-schema-id: <anonymous-schema-502>
  preferencesFile:
    description: discoverable uri for shared application preferences
    type: string
    example: /settings/prefs
    x-parser-schema-id: <anonymous-schema-498>
  primaryTopic:
    type: string
    default: '#me'
    x-parser-schema-id: <anonymous-schema-480>
  privateTypeIndex:
    description: type index for your private use
    type: string
    example: /settings/privateTypeIndex
    x-parser-schema-id: <anonymous-schema-500>
  publicTypeIndex:
    description: shared, discoverable type index
    type: string
    example: /settings/publicTypeIndex
    x-parser-schema-id: <anonymous-schema-501>
  storage:
    description: uri to your linked-data storage root
    type: string
    example: /
    x-parser-schema-id: <anonymous-schema-497>
  type:
    description: The item type (Linked-Data @type)
    enum:
      - PersonalProfileDocument
    type: string
    example: SoftwareApplication
    x-parser-schema-id: <anonymous-schema-494>
x-parser-schema-id: <anonymous-schema-492>

