title: Service
description: A service provided by an organization.
x-kind: Service
type: object
properties:
  areaServed:
    type: object
    description: a physical location
    title: Place
    x-range:
      - Place
      - City
      - State
      - PostalCode
      - GeoCircle
      - GeoShape
    properties:
      type:
        type: string
        description: The item type (Linked-Data @type)
        enum:
          - Place
        x-parser-schema-id: <anonymous-schema-336>
      address:
        type: object
        x-range: PostalAddress
        description: A physical address.
        example:
          type: PostalAddress
          name: Home
          addressCountry: USA
          addressCounty: Gotham County
          addressLocality: Gotham City
          addressRegion: New Jersey
          addressSubdivision: Gotham Heights
          postalCode: '10010'
          postOfficeBoxNumber: Box 1234
          streetAddress: 1007 Mountain Gate Rd
        x-parser-schema-id: <anonymous-schema-337>
      geo:
        type: object
        description: a geo shape (circle or box)
        x-range:
          - GeoCircle
          - GeoShape
        example:
          type: GeoShape
          geoMidpoint:
            type: GeoCoordinates,
            longitude: '73.98'
            latitude: '40.75'
          geoRadius:
            type: QuantitativeValue,
            value: 10,
            unitCode: mi,
            unitText: miles
          box: (33.5697,-117.775),(33.6018,-117.707)
        x-parser-schema-id: <anonymous-schema-338>
    x-parser-schema-id: Place
  name:
    type: string
    description: name of the service.
    x-parser-schema-id: <anonymous-schema-587>
  type:
    type: string
    enum:
      - Service
    x-parser-schema-id: <anonymous-schema-586>
x-parser-schema-id: Service
$id: http://realestate.yodata.me/schema/Service.yaml

