env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - standard
  - next
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - jest
rules: {}

ignorePatterns:
  - '!**/src/**/*'
  - 'src/asyncapi'
  - 'src/template'
