title: Service
description: A service provided by an organization.
x-kind: Service
type: object
properties:
  type:
    type: string
    enum:
      - Service
  name:
    type: string
    description: name of the service.
  areaServed:
    $ref: Place.yaml
