x-debug: false
title: Action
type: object
properties:
  topic:
    description: the subscription event type(s) assigned to the action
    type: array
    items:
      type: string

  type:
    type: string

  agent:
    description: the direct performer or driver of the action.
    x-range:
      - Person
      - Organization
      - URI
    oneOf:
      - type: string
        format: uri
        example: http://user.example.com/profile/card#me
      - type: object

  object:
    description: The object upon the action is carried out, whose state is kept intact or changed.
    type: object

  result:
    description: a result produced in the action.
    type: object

required:
  - 'type'
