title: Action
type: object
required:
  - 'type'
properties:
  type:
    description: the action type
    type: string
    enum:
    - Action
  object:
    description: the object upon which the action is carried out
    type: object
  agent:
    description: the direct performer of the action
  instrument:
    $ref: instrument.yaml
externalDocs:
  description: schema.org/Action
  url: https://schema.org/Action