title: Action
type: object
properties:
  type:
    type: string

  agent:
    description: the direct performer or driver of the action.
    x-range:
      - Person
      - Organization
      - URI
    oneOf:
      - type: string
        format: uri
        example: http://user.example.com/profile/card
      - type: object

  object:
    description: The object upon the action is carried out, whose state is kept intact or changed.
    type: object

required:
  - 'type'
