allOf:
  - $ref: ProfileDocument.yaml
  - type: object
    required:
      - id
      - type
      - inbox
      - outbox
    properties:
      id:
        type: string
        format: uri
        example: https://user.example.com/profile/card#me
      type:
        type: string
        example: SoftwareApplication
      inbox:
        description: discoverable uri to your LDN inbox
        type: string
        example: /inbox/
      outbox:
        description: discoverable uri to your LDN outbox
        type: string
        example: /outbox/
      storage:
        description: uri to your linked-data storage root
        type: string
        example: /
      preferencesFile:
        description: discoverable uri for shared application preferences
        type: string
        example: /settings/prefs
      account:
        description: discoverable solid:account root
        type: string
        example: '/'
      privateTypeIndex:
        description: type index for your private use
        type: string
        example: '/settings/privateTypeIndex'
      publicTypeIndex:
        description: shared, discoverable type index
        type: string
        example: '/settings/publicTypeIndex'
      permissions:
        type: array
        items:
          type: string
          enum:
            - profile:subscribe
            - profile:publish
            - contact:subscribe
            - contact:publish
            - lead:subscribe
            - lead:publish
            - listing:subscribe
            - listing:publish
